---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-service
  namespace: secret-service
  labels:
    app: secret-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-service
  template:
    metadata:
      labels:
        app: secret-service
    spec:
      containers:
        - name: secret-service
          image: ${IMAGE}
          ports:
            - containerPort: 8080
              name: server
      env:
