---
apiVersion: v1
kind: Service
metadata:
    name: secret-service
    namespace: secret-service
    labels:
        app: secret-service
spec:
    type: LoadBalancer
    selector:
        app: secret-service
    ports:
    - port: 80
      protocol: TCP  
      targetPort: 8080
