apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-${NAMESPACE}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ${GIT_REPO}
    targetRevision: HEAD
    path: argocd/secret-service-app/${NAMESPACE}
  destination: 
    server: ${SERVER}
    namespace: gitops-multienv