apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-${NAMESPACE}
spec:
  project: default

  source:
    repoURL: ${GIT_REPO}
    targetRevision: HEAD
    path: argocd/overlays/${NAMESPACE}
  destination: 
    server: ${SERVER}
    namespace: secret-service

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true 
