bases:
- ../../base

patches:
- target:
    kind: Deployment
    name: secret-service
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: 382630266647.dkr.ecr.eu-north-1.amazonaws.com/secret-service-app:latest
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: VAULT_ADDR
        value: "$VAULT_ADDR"
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: VAULT_TOKEN
        value: "$VAULT_TOKEN"