bases:
- ../../base

patches:
- target:
    kind: Deployment
    name: secret-service
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: 382630266647.dkr.ecr.eu-north-1.amazonaws.com/secret-service-app:latest
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: VAULT_ADDR
        value: "http://a95ae176648b54761a4121ec9e46d245-495271892.eu-north-1.elb.amazonaws.com:8200"
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: VAULT_TOKEN
        value: "hvs.TDovAzVh6XUeDQ5nB5u7rDMo"